const data={Students:[{sid:'S01',name:'Aarav',major:'CS',year:2},{sid:'S02',name:'Diya',major:'Math',year:3},{sid:'S03',name:'Kabir',major:'CS',year:2},{sid:'S04',name:'Meera',major:'Physics',year:1},{sid:'S05',name:'Riya',major:'CS',year:3}],Courses:[{cid:'C101',title:'Databases',dept:'CS',credits:4},{cid:'C102',title:'Algorithms',dept:'CS',credits:4},{cid:'M201',title:'Statistics',dept:'Math',credits:3},{cid:'P101',title:'Mechanics',dept:'Physics',credits:3}],Enrollments:[{sid:'S01',cid:'C101',semester:'Fall'},{sid:'S01',cid:'C102',semester:'Fall'},{sid:'S02',cid:'M201',semester:'Fall'},{sid:'S03',cid:'C101',semester:'Spring'},{sid:'S05',cid:'C101',semester:'Fall'}]};
const operators=[['σ','Selection','Keeps rows satisfying a condition.'],['π','Projection','Keeps only named columns.'],['⋈','Natural join','Combines matching rows on common fields.'],['∪','Union','Combines compatible relations.'],['−','Difference','Keeps rows only in the left relation.'],['×','Product','Pairs every left row with every right row.']];
const examples=[
 ['CS sophomores','π name, major (σ major = CS AND year = 2 (Students))','Names and majors of Aarav and Kabir.'],
 ['Course roster','π name, title (Students ⋈ Enrollments ⋈ Courses)','Students matched with the courses they take.'],
 ['CS courses','σ dept = CS (Courses)','Databases and Algorithms.'],
 ['First-year or Physics','σ year = 1 (Students) ∪ σ major = Physics (Students)','Meera, with duplicates removed.'],
 ['Unenrolled students','Students − (Students ⋈ Enrollments)','Students not found in an enrollment match.']
];
let lastRun=null, history=JSON.parse(localStorage.getItem('rav-history')||'[]'), stepIndex=-1;
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function rows(name,rs,cols){return {name,rows:rs,cols:cols||Object.keys(rs[0]||{})}}
function stripOuter(s){s=s.trim();if(s[0]==='('&&s.at(-1)===')'){let d=0;for(let i=0;i<s.length;i++){if(s[i]==='(')d++;if(s[i]===')')d--;if(d===0&&i<s.length-1)return s}return s.slice(1,-1).trim()}return s}
function topOp(s, chars){let d=0;for(let i=0;i<s.length;i++){if(s[i]==='(')d++;else if(s[i]===')')d--;else if(!d&&chars.includes(s[i]))return [i,s[i]]}return null}
function parse(expr, steps=[]){let s=expr.trim();while(s[0]==='('&&s.at(-1)===')')s=stripOuter(s);let op=topOp(s,'∪∩−×');if(op){let [i,x]=op,a=parse(s.slice(0,i),steps),b=parse(s.slice(i+1),steps);if(x==='∪'||x==='∩'||x==='−'){if(a.cols.join()!==b.cols.join())throw Error('Set operations require relations with the same columns.');let keys=r=>JSON.stringify(a.cols.map(c=>r[c])), A=new Map(a.rows.map(r=>[keys(r),r])),B=new Map(b.rows.map(r=>[keys(r),r]));let out=x==='∪'?[...new Map([...A,...B]).values()]:x==='∩'?[...A].filter(([k])=>B.has(k)).map(x=>x[1]):[...A].filter(([k])=>!B.has(k)).map(x=>x[1]);steps.push({kind:{'∪':'UNION','∩':'INTERSECTION','−':'DIFFERENCE'}[x],text:`${x==='∪'?'Merge':x==='∩'?'Keep shared':'Remove matching'} tuples from ${a.name} and ${b.name}.`,input:a.rows.length+b.rows.length,output:out.length});return rows(`(${a.name} ${x} ${b.name})`,out,a.cols)}let out=[];a.rows.forEach(l=>b.rows.forEach(r=>out.push({...l,...r})));let cols=[...new Set([...a.cols,...b.cols])];steps.push({kind:'PRODUCT',text:`Pair every row of ${a.name} with every row of ${b.name}.`,input:a.rows.length+b.rows.length,output:out.length});return rows(`${a.name} × ${b.name}`,out,cols)}
 let ji=s.indexOf('⋈');if(ji>0){let a=parse(s.slice(0,ji),steps),b=parse(s.slice(ji+1),steps), common=a.cols.filter(c=>b.cols.includes(c));if(!common.length)throw Error('Natural join needs at least one shared column.');let out=[];a.rows.forEach(l=>b.rows.forEach(r=>{if(common.every(c=>String(l[c])===String(r[c])))out.push({...l,...r})}));let cols=[...new Set([...a.cols,...b.cols])];steps.push({kind:'JOIN',text:`Match ${a.name} with ${b.name} where ${common.join(', ')} values agree.`,input:a.rows.length+b.rows.length,output:out.length});return rows(`${a.name} ⋈ ${b.name}`,out,cols)}
 let m=s.match(/^([σπρ])\s*([^()]+?)\s*\((.*)\)$/s);if(m){let [,x,arg,inner]=m,a=parse(inner,steps);if(x==='σ'){let cond=arg.trim(), parts=cond.split(/\s+AND\s+/i);let out=a.rows.filter(r=>parts.every(p=>{let q=p.match(/^([\w]+)\s*(=|!=|>=|<=|>|<)\s*['"]?([^'"]+)['"]?$/);if(!q)throw Error(`Cannot read condition “${p}”. Use column = value.`);let [,c,o,v]=q;if(!a.cols.includes(c))throw Error(`Column “${c}” is not in ${a.name}.`);let l=r[c], n=Number(v), right=Number.isNaN(n)?v:n;return ({'=':l==right,'!=':l!=right,'>':l>right,'<':l<right,'>=':l>=right,'<=':l<=right})[o]}));steps.push({kind:'SELECT',text:`Filter ${a.name} using the condition “${cond}”.`,input:a.rows.length,output:out.length});return rows(`σ ${cond} (${a.name})`,out,a.cols)}if(x==='π'){let cols=arg.split(',').map(x=>x.trim()).filter(Boolean);cols.forEach(c=>{if(!a.cols.includes(c))throw Error(`Column “${c}” is not in ${a.name}.`)});let seen=new Set,out=a.rows.map(r=>Object.fromEntries(cols.map(c=>[c,r[c]]))).filter(r=>{let k=JSON.stringify(r);if(seen.has(k))return false;seen.add(k);return true});steps.push({kind:'PROJECT',text:`Keep only ${cols.join(', ')} and remove duplicate tuples.`,input:a.rows.length,output:out.length});return rows(`π ${cols.join(', ')} (${a.name})`,out,cols)}if(x==='ρ'){let newName=arg.trim();steps.push({kind:'RENAME',text:`Give relation ${a.name} the new name “${newName}”.`,input:a.rows.length,output:a.rows.length});return rows(newName,a.rows,a.cols)}}
 if(!data[s])throw Error(`Unknown relation “${s}”. Try Students, Courses, or Enrollments.`);steps.push({kind:'SOURCE',text:`Start with the ${s} relation.`,input:data[s].length,output:data[s].length});return rows(s,data[s],Object.keys(data[s][0]))}
function render(result, steps){lastRun={result,steps,expression:$('#expression').value};$('#flow').innerHTML=steps.map((s,i)=>`<div class="flow-node ${i===stepIndex?'current':''}"><span class="node-kind">${s.kind}</span><strong>${s.output} tuples</strong><small>${s.input} → ${s.output} rows</small></div>${i<steps.length-1?'<span class="arrow">→</span>':''}`).join('');$('#resultTable thead').innerHTML='<tr>'+result.cols.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr>';$('#resultTable tbody').innerHTML=result.rows.length?result.rows.map(r=>'<tr>'+result.cols.map(c=>`<td>${esc(r[c]??'')}</td>`).join('')+'</tr>').join(''):`<tr><td colspan="${result.cols.length}">No tuples match this expression.</td></tr>`;$('#rowCount').textContent=`${result.rows.length} row${result.rows.length===1?'':'s'}`;$('#resultName').textContent=result.name;$('#resultMeta').textContent=`${result.cols.length} attributes · set semantics`;$('#explanation').innerHTML=steps.map((s,i)=>`<div class="step-explain" ${stepIndex>=0&&i!==stepIndex?'style="opacity:.42"':''}><h4>Step ${i+1} · ${s.kind}</h4><p>${esc(s.text)} <b>${s.output}</b> tuple${s.output===1?'':'s'} remain.</p></div>`).join('');let final=steps.at(-1);$('#insightText').textContent=final.output===0?'An empty relation is still a valid result—your query simply found no matching tuples.':`This expression transforms data in ${steps.length} operation${steps.length===1?'':'s'}, ending with ${final.output} tuple${final.output===1?'':'s'}.`}
function run(){try{let steps=[],result=parse($('#expression').value,steps);stepIndex=-1;render(result,steps);$('#status').textContent='VALID';$('#status').className='status';let e=$('#expression').value.trim();history=[e,...history.filter(x=>x!==e)].slice(0,6);localStorage.setItem('rav-history',JSON.stringify(history));renderHistory()}catch(e){$('#status').textContent='CHECK INPUT';$('#status').className='status error';toast(e.message)}}
function renderCards(){$('#relationCards').innerHTML=Object.entries(data).map(([n,r])=>`<div class="relation-card"><code>${n}</code><span>${r.length} tuples · ${Object.keys(r[0]).length} attrs</span></div>`).join('')};function renderHistory(){$('#history').innerHTML=history.length?history.map(x=>`<li title="${esc(x)}">${esc(x)}</li>`).join(''):'<li>No saved runs yet.</li>';[...$('#history').children].forEach((el,i)=>el.onclick=()=>{if(history[i]){$('#expression').value=history[i];run()}})}function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),3300)}
$('#operatorGrid').innerHTML=operators.map(x=>`<div class="operator"><code>${x[0]}</code><strong>${x[1]}</strong><p>${x[2]}</p></div>`).join('');$('#exampleGrid').innerHTML=examples.map((x,i)=>`<button class="example" data-i="${i}"><span>${esc(x[1])}</span><h3>0${i+1}. ${x[0]}</h3><p>${x[2]}</p></button>`).join('');document.querySelectorAll('.example').forEach(b=>b.onclick=()=>{$('#expression').value=examples[b.dataset.i][1];run();$('#workspace').scrollIntoView({behavior:'smooth'})});$('#runBtn').onclick=run;$('#stepBtn').onclick=()=>{if(!lastRun)run();if(lastRun){stepIndex=(stepIndex+1)%lastRun.steps.length;render(lastRun.result,lastRun.steps)}};$('#loadDemo').onclick=()=>{$('#expression').value='π name, title (Students ⋈ Enrollments ⋈ Courses)';run()};$('#clearHistory').onclick=()=>{history=[];localStorage.removeItem('rav-history');renderHistory()};$('#resetData').onclick=()=>toast('Sample relations restored.');$('#themeToggle').onclick=()=>{document.body.classList.toggle('dark');$('#themeToggle').textContent=document.body.classList.contains('dark')?'☀':'☾'};$('#exportBtn').onclick=()=>{if(!lastRun)return toast('Run an expression before exporting.');let r=lastRun.result, report=`RA•VISION QUERY REPORT\nGenerated: ${new Date().toLocaleString()}\n\nExpression\n${lastRun.expression}\n\nExecution steps\n${lastRun.steps.map((s,i)=>`${i+1}. ${s.kind}: ${s.text} (${s.output} tuples)`).join('\n')}\n\nResult (${r.rows.length} rows)\n${[r.cols.join(','),...r.rows.map(x=>r.cols.map(c=>JSON.stringify(x[c]??'')).join(','))].join('\n')}`;let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([report],{type:'text/plain'}));a.download='relational-algebra-report.txt';a.click();URL.revokeObjectURL(a.href);toast('Report downloaded.');};document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key==='Enter'){e.preventDefault();run()}});renderCards();renderHistory();run();
